#!/usr/bin/env python3
"""Generate a C source file embedding tree-sitter query strings.

Usage: embed_queries.py <query-dir>

Scans <query-dir>/*/highlights.scm and emits C code to stdout.
"""

import os
import sys


def escape_c_string(s):
    """Escape a string for embedding in a C string literal."""
    result = []
    for ch in s:
        if ch == '\\':
            result.append('\\\\')
        elif ch == '"':
            result.append('\\"')
        elif ch == '\n':
            result.append('\\n')
        elif ch == '\r':
            result.append('\\r')
        elif ch == '\t':
            result.append('\\t')
        elif ch == '\0':
            result.append('\\0')
        elif ord(ch) < 32 or ord(ch) == 127:
            result.append(f'\\x{ord(ch):02x}')
        else:
            result.append(ch)
    return ''.join(result)


def sanitize_lang(name):
    """Turn a language directory name into a valid C identifier fragment."""
    return name.replace('-', '_').replace('.', '_').replace('+', 'p')


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <query-dir>", file=sys.stderr)
        sys.exit(1)

    query_dir = sys.argv[1]
    if not os.path.isdir(query_dir):
        print(f"Error: {query_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    # Collect (lang_name, file_path) pairs sorted by language name
    langs = []
    for entry in sorted(os.listdir(query_dir)):
        highlights = os.path.join(query_dir, entry, "highlights.scm")
        if os.path.isfile(highlights):
            langs.append((entry, highlights))

    if not langs:
        print(f"Warning: no */highlights.scm found in {query_dir}", file=sys.stderr)

    # Emit C source
    print("/* Generated by embed_queries.py — do not edit */")
    print()
    print("#include <string.h>")
    print()

    # Emit each query as a static const char array
    for lang, path in langs:
        with open(path, 'r') as f:
            content = f.read()

        c_id = sanitize_lang(lang)

        # Split into lines and emit as concatenated string literals
        lines = content.split('\n')
        print(f"static const char ts_query_{c_id}[] =")
        for i, line in enumerate(lines):
            escaped = escape_c_string(line)
            if i < len(lines) - 1:
                print(f'  "{escaped}\\n"')
            else:
                # Last line: no trailing \n if it was empty (from trailing newline)
                if escaped:
                    print(f'  "{escaped}"')
        print("  ;")
        print()

    # Emit ts_embedded_query_get
    print("const char *ts_embedded_query_get(const char *lang) {")
    for lang, _ in langs:
        c_id = sanitize_lang(lang)
        print(f'    if (strcmp(lang, "{lang}") == 0) return ts_query_{c_id};')
    print("    return NULL;")
    print("}")
    print()

    # Emit ts_embedded_query_len
    print("int ts_embedded_query_len(const char *lang) {")
    for lang, _ in langs:
        c_id = sanitize_lang(lang)
        print(f'    if (strcmp(lang, "{lang}") == 0) return sizeof(ts_query_{c_id}) - 1;')
    print("    return 0;")
    print("}")


if __name__ == "__main__":
    main()
