/* jsh_coreutils_stubs.c — Stubs for Rust uutils coreutils FFI symbols.
 *
 * In the static jemacs-qt binary, the Rust libjsh_coreutils.a is not available.
 * These stubs allow the binary to link; at runtime, coreutils commands invoked
 * through the in-process jsh shell will return an error. Commands run via the
 * vterm PTY terminal use external binaries and are unaffected.
 */
#include <stdio.h>

#define JSH_STUB(name) \
    int name(int argc, const char **argv) { \
        fprintf(stderr, #name ": not available in static build\n"); \
        return 1; \
    }

JSH_STUB(jsh_arch)
JSH_STUB(jsh_b2sum)
JSH_STUB(jsh_base32)
JSH_STUB(jsh_base64)
JSH_STUB(jsh_basename)
JSH_STUB(jsh_basenc)
JSH_STUB(jsh_cat)
JSH_STUB(jsh_chgrp)
JSH_STUB(jsh_chmod)
JSH_STUB(jsh_chown)
JSH_STUB(jsh_chroot)
JSH_STUB(jsh_cksum)
JSH_STUB(jsh_comm)
JSH_STUB(jsh_cp)
JSH_STUB(jsh_csplit)
JSH_STUB(jsh_cu_realpath)
JSH_STUB(jsh_cut)
JSH_STUB(jsh_date)
JSH_STUB(jsh_dd)
JSH_STUB(jsh_df)
JSH_STUB(jsh_dir)
JSH_STUB(jsh_dircolors)
JSH_STUB(jsh_dirname)
JSH_STUB(jsh_du)
JSH_STUB(jsh_echo)
JSH_STUB(jsh_env)
JSH_STUB(jsh_expand)
JSH_STUB(jsh_expr)
JSH_STUB(jsh_factor)
JSH_STUB(jsh_fmt)
JSH_STUB(jsh_fold)
JSH_STUB(jsh_grep)
JSH_STUB(jsh_groups)
JSH_STUB(jsh_head)
JSH_STUB(jsh_hostname)
JSH_STUB(jsh_id)
JSH_STUB(jsh_install)
JSH_STUB(jsh_join)
JSH_STUB(jsh_kill)
JSH_STUB(jsh_link)
JSH_STUB(jsh_ln)
JSH_STUB(jsh_logname)
JSH_STUB(jsh_ls)
JSH_STUB(jsh_md5sum)
JSH_STUB(jsh_mkdir)
JSH_STUB(jsh_mkfifo)
JSH_STUB(jsh_mknod)
JSH_STUB(jsh_mktemp)
JSH_STUB(jsh_mv)
JSH_STUB(jsh_nice)
JSH_STUB(jsh_nl)
JSH_STUB(jsh_nohup)
JSH_STUB(jsh_nproc)
JSH_STUB(jsh_numfmt)
JSH_STUB(jsh_od)
JSH_STUB(jsh_paste)
JSH_STUB(jsh_pathchk)
JSH_STUB(jsh_pr)
JSH_STUB(jsh_printenv)
JSH_STUB(jsh_printf)
JSH_STUB(jsh_ptx)
JSH_STUB(jsh_pwd)
JSH_STUB(jsh_readlink)
JSH_STUB(jsh_rm)
JSH_STUB(jsh_rmdir)
JSH_STUB(jsh_seq)
JSH_STUB(jsh_sha1sum)
JSH_STUB(jsh_sha224sum)
JSH_STUB(jsh_sha256sum)
JSH_STUB(jsh_sha384sum)
JSH_STUB(jsh_sha512sum)
JSH_STUB(jsh_shred)
JSH_STUB(jsh_shuf)
JSH_STUB(jsh_sleep)
JSH_STUB(jsh_sort)
JSH_STUB(jsh_split)
JSH_STUB(jsh_stat)
JSH_STUB(jsh_stty)
JSH_STUB(jsh_sum)
JSH_STUB(jsh_sync)
JSH_STUB(jsh_tac)
JSH_STUB(jsh_tail)
JSH_STUB(jsh_tee)
JSH_STUB(jsh_test)
JSH_STUB(jsh_timeout)
JSH_STUB(jsh_touch)
JSH_STUB(jsh_tr)
JSH_STUB(jsh_truncate)
JSH_STUB(jsh_tsort)
JSH_STUB(jsh_tty)
JSH_STUB(jsh_uname)
JSH_STUB(jsh_unexpand)
JSH_STUB(jsh_uniq)
JSH_STUB(jsh_unlink)
JSH_STUB(jsh_vdir)
JSH_STUB(jsh_wc)
JSH_STUB(jsh_whoami)
JSH_STUB(jsh_yes)
JSH_STUB(jsh_hostid)
JSH_STUB(jsh_pinky)
JSH_STUB(jsh_uptime)
JSH_STUB(jsh_users)
JSH_STUB(jsh_who)
