/*
 * treesitter_shim.c — Tree-sitter integration for Chez Scheme FFI.
 *
 * Wraps the tree-sitter C API with flat functions suitable for Chez
 * foreign-procedure calls.  TSNode (24-byte struct) is handled via
 * static node slots since Chez FFI cannot pass structs by value.
 *
 * Compile (dynamic):
 *   gcc -shared -fPIC -O2 -o treesitter_shim.so treesitter_shim.c \
 *       -ltree-sitter -Wall
 *
 * For static linking the grammar language functions (tree_sitter_c, etc.)
 * are resolved at link time from per-language .a archives.
 */

#include <tree_sitter/api.h>
#include <string.h>
#include <stdlib.h>

/* ========================================================================
 * Language registry — extern declarations for statically linked grammars.
 * Each grammar archive exports a single tree_sitter_<lang>() function.
 * ======================================================================== */

extern const TSLanguage *tree_sitter_c(void);
extern const TSLanguage *tree_sitter_cpp(void);
extern const TSLanguage *tree_sitter_python(void);
extern const TSLanguage *tree_sitter_javascript(void);
extern const TSLanguage *tree_sitter_rust(void);
extern const TSLanguage *tree_sitter_go(void);
extern const TSLanguage *tree_sitter_bash(void);
extern const TSLanguage *tree_sitter_json(void);
extern const TSLanguage *tree_sitter_ruby(void);
extern const TSLanguage *tree_sitter_java(void);
extern const TSLanguage *tree_sitter_css(void);
extern const TSLanguage *tree_sitter_html(void);
extern const TSLanguage *tree_sitter_yaml(void);
extern const TSLanguage *tree_sitter_toml(void);
extern const TSLanguage *tree_sitter_lua(void);
extern const TSLanguage *tree_sitter_sql(void);
extern const TSLanguage *tree_sitter_markdown(void);
extern const TSLanguage *tree_sitter_scheme(void);

/* Embedded highlight queries (generated by embed_queries.py) */
extern const char *ts_embedded_query_get(const char *lang);
extern int ts_embedded_query_len(const char *lang);

/* ========================================================================
 * Language lookup
 * ======================================================================== */

const TSLanguage *ts_shim_language_get(const char *name) {
    if (!name) return NULL;
    if (strcmp(name, "c") == 0)          return tree_sitter_c();
    if (strcmp(name, "cpp") == 0)        return tree_sitter_cpp();
    if (strcmp(name, "python") == 0)     return tree_sitter_python();
    if (strcmp(name, "javascript") == 0) return tree_sitter_javascript();
    if (strcmp(name, "rust") == 0)       return tree_sitter_rust();
    if (strcmp(name, "go") == 0)         return tree_sitter_go();
    if (strcmp(name, "bash") == 0)       return tree_sitter_bash();
    if (strcmp(name, "json") == 0)       return tree_sitter_json();
    if (strcmp(name, "ruby") == 0)       return tree_sitter_ruby();
    if (strcmp(name, "java") == 0)       return tree_sitter_java();
    if (strcmp(name, "css") == 0)        return tree_sitter_css();
    if (strcmp(name, "html") == 0)       return tree_sitter_html();
    if (strcmp(name, "yaml") == 0)       return tree_sitter_yaml();
    if (strcmp(name, "toml") == 0)       return tree_sitter_toml();
    if (strcmp(name, "lua") == 0)        return tree_sitter_lua();
    if (strcmp(name, "sql") == 0)        return tree_sitter_sql();
    if (strcmp(name, "markdown") == 0)   return tree_sitter_markdown();
    if (strcmp(name, "scheme") == 0)     return tree_sitter_scheme();
    return NULL;
}

/* ========================================================================
 * Parser lifecycle
 * ======================================================================== */

void *ts_shim_parser_new(void) {
    return (void *)ts_parser_new();
}

void ts_shim_parser_delete(void *parser) {
    if (parser) ts_parser_delete((TSParser *)parser);
}

/* Returns 1 on success, 0 on failure (unknown language). */
int ts_shim_parser_set_language(void *parser, const char *lang_name) {
    const TSLanguage *lang = ts_shim_language_get(lang_name);
    if (!lang) return 0;
    return ts_parser_set_language((TSParser *)parser, lang) ? 1 : 0;
}

/* ========================================================================
 * Parsing
 * ======================================================================== */

/* Full parse (or re-parse with old_tree for incremental). */
void *ts_shim_parse_string(void *parser, void *old_tree,
                           const char *src, int src_len) {
    TSTree *tree = ts_parser_parse_string(
        (TSParser *)parser, (TSTree *)old_tree, src, (uint32_t)src_len);
    return (void *)tree;
}

/* Apply an edit to the old tree, then re-parse incrementally. */
void *ts_shim_parse_incremental(void *parser, void *old_tree,
                                const char *src, int src_len,
                                int start_byte, int old_end_byte, int new_end_byte,
                                int start_row, int start_col,
                                int old_end_row, int old_end_col,
                                int new_end_row, int new_end_col) {
    if (!old_tree) {
        /* No old tree — full parse */
        return ts_shim_parse_string(parser, NULL, src, src_len);
    }
    TSInputEdit edit = {
        .start_byte    = (uint32_t)start_byte,
        .old_end_byte  = (uint32_t)old_end_byte,
        .new_end_byte  = (uint32_t)new_end_byte,
        .start_point   = { (uint32_t)start_row,   (uint32_t)start_col },
        .old_end_point = { (uint32_t)old_end_row,  (uint32_t)old_end_col },
        .new_end_point = { (uint32_t)new_end_row,  (uint32_t)new_end_col },
    };
    ts_tree_edit((TSTree *)old_tree, &edit);
    return ts_shim_parse_string(parser, old_tree, src, src_len);
}

void ts_shim_tree_delete(void *tree) {
    if (tree) ts_tree_delete((TSTree *)tree);
}

/* ========================================================================
 * Node slots — TSNode is a 24-byte struct, can't pass by value via FFI.
 * We keep a small array of node scratch slots.
 * ======================================================================== */

#define NUM_NODE_SLOTS 8
static TSNode node_slots[NUM_NODE_SLOTS];

void ts_shim_tree_root_node(void *tree, int slot) {
    if (tree && slot >= 0 && slot < NUM_NODE_SLOTS) {
        node_slots[slot] = ts_tree_root_node((TSTree *)tree);
    }
}

int ts_shim_node_start_byte(int slot) {
    if (slot < 0 || slot >= NUM_NODE_SLOTS) return 0;
    return (int)ts_node_start_byte(node_slots[slot]);
}

int ts_shim_node_end_byte(int slot) {
    if (slot < 0 || slot >= NUM_NODE_SLOTS) return 0;
    return (int)ts_node_end_byte(node_slots[slot]);
}

int ts_shim_node_start_row(int slot) {
    if (slot < 0 || slot >= NUM_NODE_SLOTS) return 0;
    return (int)ts_node_start_point(node_slots[slot]).row;
}

int ts_shim_node_start_col(int slot) {
    if (slot < 0 || slot >= NUM_NODE_SLOTS) return 0;
    return (int)ts_node_start_point(node_slots[slot]).column;
}

int ts_shim_node_end_row(int slot) {
    if (slot < 0 || slot >= NUM_NODE_SLOTS) return 0;
    return (int)ts_node_end_point(node_slots[slot]).row;
}

int ts_shim_node_end_col(int slot) {
    if (slot < 0 || slot >= NUM_NODE_SLOTS) return 0;
    return (int)ts_node_end_point(node_slots[slot]).column;
}

const char *ts_shim_node_type(int slot) {
    if (slot < 0 || slot >= NUM_NODE_SLOTS) return "";
    return ts_node_type(node_slots[slot]);
}

int ts_shim_node_child_count(int slot) {
    if (slot < 0 || slot >= NUM_NODE_SLOTS) return 0;
    return (int)ts_node_child_count(node_slots[slot]);
}

int ts_shim_node_named_child_count(int slot) {
    if (slot < 0 || slot >= NUM_NODE_SLOTS) return 0;
    return (int)ts_node_named_child_count(node_slots[slot]);
}

/* Copy child node into a different slot. */
void ts_shim_node_child(int src_slot, int child_idx, int dst_slot) {
    if (src_slot < 0 || src_slot >= NUM_NODE_SLOTS) return;
    if (dst_slot < 0 || dst_slot >= NUM_NODE_SLOTS) return;
    node_slots[dst_slot] = ts_node_child(node_slots[src_slot], (uint32_t)child_idx);
}

void ts_shim_node_named_child(int src_slot, int child_idx, int dst_slot) {
    if (src_slot < 0 || src_slot >= NUM_NODE_SLOTS) return;
    if (dst_slot < 0 || dst_slot >= NUM_NODE_SLOTS) return;
    node_slots[dst_slot] = ts_node_named_child(node_slots[src_slot], (uint32_t)child_idx);
}

int ts_shim_node_is_null(int slot) {
    if (slot < 0 || slot >= NUM_NODE_SLOTS) return 1;
    return ts_node_is_null(node_slots[slot]) ? 1 : 0;
}

/* ========================================================================
 * Query / Highlighting
 * ======================================================================== */

/* Create a compiled query. Returns query pointer or NULL on error.
 * error_offset and error_type are output parameters. */
void *ts_shim_query_new(const char *lang_name, const char *query_src, int query_len,
                        int *error_offset, int *error_type) {
    const TSLanguage *lang = ts_shim_language_get(lang_name);
    if (!lang) return NULL;

    uint32_t err_off = 0;
    TSQueryError err_type = TSQueryErrorNone;
    TSQuery *query = ts_query_new(lang, query_src, (uint32_t)query_len,
                                  &err_off, &err_type);
    if (error_offset) *error_offset = (int)err_off;
    if (error_type)   *error_type = (int)err_type;
    return (void *)query;
}

void ts_shim_query_delete(void *query) {
    if (query) ts_query_delete((TSQuery *)query);
}

int ts_shim_query_pattern_count(void *query) {
    if (!query) return 0;
    return (int)ts_query_pattern_count((TSQuery *)query);
}

int ts_shim_query_capture_count(void *query) {
    if (!query) return 0;
    return (int)ts_query_capture_count((TSQuery *)query);
}

/* ========================================================================
 * Query cursor — iteration over matches/captures
 * ======================================================================== */

void *ts_shim_query_cursor_new(void) {
    return (void *)ts_query_cursor_new();
}

void ts_shim_query_cursor_delete(void *cursor) {
    if (cursor) ts_query_cursor_delete((TSQueryCursor *)cursor);
}

void ts_shim_query_cursor_exec(void *cursor, void *query, int node_slot) {
    if (!cursor || !query) return;
    if (node_slot < 0 || node_slot >= NUM_NODE_SLOTS) return;
    ts_query_cursor_exec((TSQueryCursor *)cursor,
                         (TSQuery *)query,
                         node_slots[node_slot]);
}

void ts_shim_query_cursor_set_byte_range(void *cursor, int start, int end) {
    if (!cursor) return;
    ts_query_cursor_set_byte_range((TSQueryCursor *)cursor,
                                  (uint32_t)start, (uint32_t)end);
}

/* ========================================================================
 * Batch highlight capture — the performance-critical function.
 *
 * Instead of iterating capture-by-capture across FFI (expensive),
 * this function fills a flat int array with (start_byte, end_byte, capture_index)
 * triples.  The Scheme side reads the array once and maps capture indices to
 * style IDs using ts_shim_query_capture_name_for_id().
 *
 * Returns the number of captures written (each = 3 ints).
 * ======================================================================== */

int ts_shim_highlight_captures(void *cursor, void *query,
                               int *out_buf, int max_captures) {
    if (!cursor || !query || !out_buf || max_captures <= 0) return 0;

    TSQueryCursor *qc = (TSQueryCursor *)cursor;
    TSQuery *q = (TSQuery *)query;
    TSQueryMatch match;
    uint32_t capture_index;
    int count = 0;

    while (count < max_captures &&
           ts_query_cursor_next_capture(qc, &match, &capture_index)) {
        const TSQueryCapture *cap = &match.captures[capture_index];
        uint32_t start = ts_node_start_byte(cap->node);
        uint32_t end   = ts_node_end_byte(cap->node);
        out_buf[count * 3]     = (int)start;
        out_buf[count * 3 + 1] = (int)end;
        out_buf[count * 3 + 2] = (int)cap->index;
        count++;
    }
    return count;
}

/* Get the capture name for a given capture index in a query. */
const char *ts_shim_query_capture_name(void *query, int capture_index) {
    if (!query) return "";
    uint32_t len;
    return ts_query_capture_name_for_id((TSQuery *)query,
                                        (uint32_t)capture_index, &len);
}

/* ========================================================================
 * Changed ranges after incremental parse
 * ======================================================================== */

/* Returns number of ranges written (each = 2 ints: start_byte, end_byte). */
int ts_shim_tree_changed_ranges(void *old_tree, void *new_tree,
                                int *out_ranges, int max_ranges) {
    if (!old_tree || !new_tree || !out_ranges || max_ranges <= 0) return 0;

    uint32_t count = 0;
    TSRange *ranges = ts_tree_get_changed_ranges(
        (TSTree *)old_tree, (TSTree *)new_tree, &count);

    int n = (int)count;
    if (n > max_ranges) n = max_ranges;

    for (int i = 0; i < n; i++) {
        out_ranges[i * 2]     = (int)ranges[i].start_byte;
        out_ranges[i * 2 + 1] = (int)ranges[i].end_byte;
    }

    free(ranges);
    return n;
}

/* ========================================================================
 * Embedded highlight query access
 * ======================================================================== */

const char *ts_shim_get_highlight_query(const char *lang) {
    const char *q = ts_embedded_query_get(lang);
    return q ? q : "";
}

int ts_shim_get_highlight_query_len(const char *lang) {
    return ts_embedded_query_len(lang);
}
